Fix for https://github.com/riscv-software-src/riscv-tests/issues/482
riscv-software-src/riscv-tests pull request #484
Opened 2023-06-30 09:34 UTC by TommyMurphyTM1234

Fix for:

* https://github.com/riscv-software-src/riscv-tests/issues/482

Note that this fix means that the tests will probably fail to compile with a pre GCC 12 RISC-V toolchain which predates the separation of the `zicsr` (and `zifencei`) extension(s) out from the base integer ISA. But I didn't think that it was worthwhile complicating the script further by trying to cater for older toolchains in the script.

2023-06-30 16:08 UTC, timsifive commented
Note the pylint failure is not your fault, and will be fixed by #483.

2023-06-30 16:11 UTC, timsifive requested changes
Can you give the PR a title that someone can read without knowing github issue numbers by heart?

Change looks fine, but I'm a bit concerned about it not working with older GCC versions. Specifically, OpenOCD automatically runs these tests using https://github.com/riscv/riscv-openocd/blob/riscv/.github/workflows/spike-openocd-tests.yml.

Can you confirm that these new flags are supported by the toolchain referred to on line 10 of that file?

2023-06-30 18:32 UTC, TommyMurphyTM1234 commented
Thanks @timsifive .

> Can you give the PR a title that someone can read without knowing github issue numbers by heart?

Sorry - I thought that it was sufficient to link to the issue.
I will give it a more descriptive title and link to the issue in the description.

> Change looks fine, but I'm a bit concerned about it not working with older GCC versions. Specifically, OpenOCD automatically runs these tests using https://github.com/riscv/riscv-openocd/blob/riscv/.github/workflows/spike-openocd-tests.yml.
> 
> Can you confirm that these new flags are supported by the toolchain referred to on line 10 of that file?

I'm pretty sure that any post GCC 12 toolchain will support `-march=rvXX..._zicsr` but I will check with this specific version to be sure:

* https://github.com/riscv/riscv-openocd/blob/92c03192612bd7c41f4562b5f130ac8e1907d591/.github/workflows/spike-openocd-tests.yml#L10

2023-07-02 13:34 UTC, TommyMurphyTM1234 commented
> Can you give the PR a title that someone can read without knowing github issue numbers by heart?
> 
> Change looks fine, but I'm a bit concerned about it not working with older GCC versions. Specifically, OpenOCD automatically runs these tests using https://github.com/riscv/riscv-openocd/blob/riscv/.github/workflows/spike-openocd-tests.yml.
> 
> Can you confirm that these new flags are supported by the toolchain referred to on line 10 of that file?

Hi @timsifive - I can't get the tests (even without my PR) to run with this toolchain because the tests try to invoke `riscv64-unknown-elf-gcc` but the xPack toolchain uses a different prefix - `riscv-none-embed-gcc`.

* https://github.com/riscv/riscv-openocd/blob/92c03192612bd7c41f4562b5f130ac8e1907d591/.github/workflows/spike-openocd-tests.yml#L10
```
  TOOLCHAIN_URL: https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v12.2.0-1/xpack-riscv-none-elf-gcc-12.2.0-1-linux-x64.tar.gz
```
I get this:
```
make
./gdbserver.py \
	./targets/RISC-V/spike64.py \
	CeaseMultiTest \
	--isolate \
	--print-failures \
	--sim_cmd /bin/spike \
	--server_cmd /bin/openocd \
	
Using $misa from hart definition: 0x8000000000141125
[CeaseMultiTest] Starting > logs/20230702-142921-spike64-CeaseMultiTest.log
[CeaseMultiTest] not_applicable in 0.00s
::::::::::::::::::::::::::::[ ran 1 tests in 0s ]:::::::::::::::::::::::::::::
1 tests returned not_applicable
./gdbserver.py \
	./targets/RISC-V/spike64.py \
	CeaseRunTest \
	--isolate \
	--print-failures \
	--sim_cmd /bin/spike \
	--server_cmd /bin/openocd \
	
Using $misa from hart definition: 0x8000000000141125
[CeaseRunTest] Starting > logs/20230702-142922-spike64-CeaseRunTest.log
[CeaseRunTest] not_applicable in 0.00s
::::::::::::::::::::::::::::[ ran 1 tests in 0s ]:::::::::::::::::::::::::::::
1 tests returned not_applicable
./gdbserver.py \
	./targets/RISC-V/spike64.py \
	CeaseStepiTest \
	--isolate \
	--print-failures \
	--sim_cmd /bin/spike \
	--server_cmd /bin/openocd \
	
Using $misa from hart definition: 0x8000000000141125
[CeaseStepiTest] Starting > logs/20230702-142922-spike64-CeaseStepiTest.log
[CeaseStepiTest] not_applicable in 0.00s
::::::::::::::::::::::::::::[ ran 1 tests in 0s ]:::::::::::::::::::::::::::::
1 tests returned not_applicable
./gdbserver.py \
	./targets/RISC-V/spike64.py \
	CheckMisa \
	--isolate \
	--print-failures \
	--sim_cmd /bin/spike \
	--server_cmd /bin/openocd \
	
Using $misa from hart definition: 0x8000000000141125
[CheckMisa] Starting > logs/20230702-142922-spike64-CheckMisa.log
[CheckMisa] exception in 0.02s
Test: CheckMisa
Target: spike64
---------------------------------[ Compile ]----------------------------------
+ riscv64-unknown-elf-gcc -g programs/checksum.c programs/tiny-malloc.c programs/infinite_loop.S -DDEFINE_MALLOC -DDEFINE_FREE programs/entry.S programs/init.c -DNHARTS=1 -I ../env -T targets/RISC-V/spike64.lds -nostartfiles -mcmodel=medany -DXLEN=64 -o /tmp/spike64_checksum-8000000000141125_k23pr4sf -march=rv64imafc_zicsr -mabi=lp64
--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 1210, in run
    self.classSetup()
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 1265, in classSetup
    BaseTest.classSetup(self)
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 1173, in classSetup
    self.target_process = self.target.create()
  File "/home/user/Downloads/riscv-tests/debug/./targets/RISC-V/spike64.py", line 23, in create
    return testlib.Spike(self, isa="RV64IMAFC", progbufsize=0,
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 87, in __init__
    self.infinite_loop = target.compile(self.harts[0],
  File "/home/user/Downloads/riscv-tests/debug/targets.py", line 221, in compile
    return self.do_compile(hart, *sources)
  File "/home/user/Downloads/riscv-tests/debug/targets.py", line 215, in do_compile
    testlib.compile(args)
  File "/home/user/Downloads/riscv-tests/debug/testlib.py", line 53, in compile
    with subprocess.Popen(cmd, stdout=subprocess.PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'riscv64-unknown-elf-gcc'
-------------------------------[ End of logs ]--------------------------------
Result: exception
Logfile: logs/20230702-142922-spike64-CheckMisa.log
Reproduce: ./gdbserver.py ./targets/RISC-V/spike64.py CheckMisa
Time elapsed: 0.02s
::::::::::::::::::::::::::::[ ran 1 tests in 0s ]:::::::::::::::::::::::::::::
1 tests returned exception
   CheckMisa > logs/20230702-142922-spike64-CheckMisa.log
make: *** [Makefile:20: run.spike64.CheckMisa] Error 1
```

2023-07-02 13:55 UTC, TommyMurphyTM1234 commented
> Change looks fine, but I'm a bit concerned about it not working with older GCC versions. Specifically, OpenOCD automatically runs these tests using https://github.com/riscv/riscv-openocd/blob/riscv/.github/workflows/spike-openocd-tests.yml.
> 
> Can you confirm that these new flags are supported by the toolchain referred to on line 10 of that file?

Hi @timsifive - I can confirm that those tests using the xPack toolchain in question still work fine with this PR's change.
```
echo $PATH
/home/user/Downloads/xpack-riscv-none-elf-gcc-12.2.0-1/bin:/home/user/Downloads/riscv-openocd/installed-tools/bin:/home/user/Downloads/riscv-isa-sim/installed-tools/bin:/usr/lib/ccache:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

./gdbserver.py targets/RISC-V/spike32.py --print-failures --gcc riscv-none-elf-gcc --gdb riscv-none-elf-gdb 
Using $misa from hart definition: 0x4034112d
[CeaseMultiTest] Starting > logs/20230702-144023-spike32-CeaseMultiTest.log
[CeaseMultiTest] not_applicable in 0.00s
[CeaseRunTest] Starting > logs/20230702-144023-spike32-CeaseRunTest.log
[CeaseRunTest] not_applicable in 0.00s
[CeaseStepiTest] Starting > logs/20230702-144023-spike32-CeaseStepiTest.log
[CeaseStepiTest] not_applicable in 0.00s
[CheckMisa] Starting > logs/20230702-144023-spike32-CheckMisa.log
[CheckMisa] pass in 1.47s
[CustomRegisterTest] Starting > logs/20230702-144025-spike32-CustomRegisterTest.log
[CustomRegisterTest] pass in 9.89s
[DebugBreakpoint] Starting > logs/20230702-144035-spike32-DebugBreakpoint.log
[DebugBreakpoint] pass in 7.37s
[DebugChangeString] Starting > logs/20230702-144042-spike32-DebugChangeString.log
[DebugChangeString] pass in 6.82s
[DebugCompareSections] Starting > logs/20230702-144049-spike32-DebugCompareSections.log
[DebugCompareSections] pass in 4.97s
[DebugExit] Starting > logs/20230702-144054-spike32-DebugExit.log
[DebugExit] pass in 5.23s
[DebugFunctionCall] Starting > logs/20230702-144059-spike32-DebugFunctionCall.log
[DebugFunctionCall] pass in 8.06s
[DebugSymbols] Starting > logs/20230702-144107-spike32-DebugSymbols.log
[DebugSymbols] pass in 5.88s
[DebugTurbostep] Starting > logs/20230702-144113-spike32-DebugTurbostep.log
[DebugTurbostep] pass in 9.87s
[DisconnectTest] Starting > logs/20230702-144123-spike32-DisconnectTest.log
[DisconnectTest] pass in 6.33s
[DownloadTest] Starting > logs/20230702-144129-spike32-DownloadTest.log
[DownloadTest] pass in 22.99s
[EbreakTest] Starting > logs/20230702-144152-spike32-EbreakTest.log
[EbreakTest] pass in 4.86s
[EtriggerTest] Starting > logs/20230702-144157-spike32-EtriggerTest.log
[EtriggerTest] pass in 6.43s
[FreeRtosTest] Starting > logs/20230702-144203-spike32-FreeRtosTest.log
[FreeRtosTest] pass in 16.97s
[Hwbp1] Starting > logs/20230702-144220-spike32-Hwbp1.log
[Hwbp1] pass in 6.47s
[Hwbp2] Starting > logs/20230702-144227-spike32-Hwbp2.log
[Hwbp2] pass in 7.41s
[HwbpManual] Starting > logs/20230702-144234-spike32-HwbpManual.log
[HwbpManual] not_applicable in 7.04s
[IcountTest] Starting > logs/20230702-144241-spike32-IcountTest.log
[IcountTest] pass in 4.42s
[InfoTest] Starting > logs/20230702-144246-spike32-InfoTest.log
[InfoTest] pass in 1.50s
[InstantChangePc] Starting > logs/20230702-144247-spike32-InstantChangePc.log
[InstantChangePc] pass in 2.91s
[InstantHaltTest] Starting > logs/20230702-144250-spike32-InstantHaltTest.log
[InstantHaltTest] pass in 1.99s
[InterruptTest] Starting > logs/20230702-144252-spike32-InterruptTest.log
[InterruptTest] pass in 6.69s
[ItriggerTest] Starting > logs/20230702-144259-spike32-ItriggerTest.log
[ItriggerTest] pass in 4.68s
[JumpHbreak] Starting > logs/20230702-144303-spike32-JumpHbreak.log
[JumpHbreak] pass in 3.93s
[MemTest16] Starting > logs/20230702-144307-spike32-MemTest16.log
[MemTest16] pass in 1.88s
[MemTest32] Starting > logs/20230702-144309-spike32-MemTest32.log
[MemTest32] pass in 1.89s
[MemTest64] Starting > logs/20230702-144311-spike32-MemTest64.log
[MemTest64] pass in 2.02s
[MemTest8] Starting > logs/20230702-144313-spike32-MemTest8.log
[MemTest8] pass in 2.02s
[MemTestBlock0] Starting > logs/20230702-144315-spike32-MemTestBlock0.log
[MemTestBlock0] pass in 4.66s
[MemTestBlock1] Starting > logs/20230702-144320-spike32-MemTestBlock1.log
[MemTestBlock1] pass in 4.75s
[MemTestBlock2] Starting > logs/20230702-144325-spike32-MemTestBlock2.log
[MemTestBlock2] pass in 4.72s
[MemTestBlockReadInvalid] Starting > logs/20230702-144329-spike32-MemTestBlockReadInvalid.log
[MemTestBlockReadInvalid] not_applicable in 0.00s
[MemTestReadInvalid] Starting > logs/20230702-144329-spike32-MemTestReadInvalid.log
[MemTestReadInvalid] pass in 2.51s
[MemorySampleMixed] Starting > logs/20230702-144332-spike32-MemorySampleMixed.log
[MemorySampleMixed] not_applicable in 0.00s
[MemorySampleSingle] Starting > logs/20230702-144332-spike32-MemorySampleSingle.log
[MemorySampleSingle] not_applicable in 0.00s
[MulticoreRegTest] Starting > logs/20230702-144332-spike32-MulticoreRegTest.log
[MulticoreRegTest] not_applicable in 0.00s
[MulticoreRtosSwitchActiveHartTest] Starting > logs/20230702-144332-spike32-MulticoreRtosSwitchActiveHartTest.log
[MulticoreRtosSwitchActiveHartTest] not_applicable in 0.00s
[MulticoreRunAllHaltOne] Starting > logs/20230702-144332-spike32-MulticoreRunAllHaltOne.log
[MulticoreRunAllHaltOne] not_applicable in 0.00s
[PrivChange] Starting > logs/20230702-144332-spike32-PrivChange.log
[PrivChange] pass in 4.53s
[PrivRw] Starting > logs/20230702-144336-spike32-PrivRw.log
[PrivRw] pass in 5.40s
[ProgramHwWatchpoint] Starting > logs/20230702-144342-spike32-ProgramHwWatchpoint.log
[ProgramHwWatchpoint] pass in 8.39s
[ProgramSwWatchpoint] Starting > logs/20230702-144350-spike32-ProgramSwWatchpoint.log
[ProgramSwWatchpoint] pass in 16.75s
[Registers] Starting > logs/20230702-144407-spike32-Registers.log
[Registers] pass in 10.63s
[RepeatReadTest] Starting > logs/20230702-144418-spike32-RepeatReadTest.log
[RepeatReadTest] pass in 11.43s
[Semihosting] Starting > logs/20230702-144429-spike32-Semihosting.log
[Semihosting] pass in 7.50s
[SemihostingFileio] Starting > logs/20230702-144437-spike32-SemihostingFileio.log
[SemihostingFileio] pass in 7.60s
[SimpleF18Test] Starting > logs/20230702-144444-spike32-SimpleF18Test.log
[SimpleF18Test] pass in 4.02s
[SimpleNoExistTest] Starting > logs/20230702-144448-spike32-SimpleNoExistTest.log
[SimpleNoExistTest] pass in 1.42s
[SimpleS0Test] Starting > logs/20230702-144450-spike32-SimpleS0Test.log
[SimpleS0Test] pass in 3.38s
[SimpleS1Test] Starting > logs/20230702-144453-spike32-SimpleS1Test.log
[SimpleS1Test] pass in 3.36s
[SimpleT0Test] Starting > logs/20230702-144456-spike32-SimpleT0Test.log
[SimpleT0Test] pass in 3.36s
[SimpleT1Test] Starting > logs/20230702-144500-spike32-SimpleT1Test.log
[SimpleT1Test] pass in 3.38s
[SimpleV13Test] Starting > logs/20230702-144503-spike32-SimpleV13Test.log
[SimpleV13Test] pass in 11.91s
[SmpSimultaneousRunHalt] Starting > logs/20230702-144515-spike32-SmpSimultaneousRunHalt.log
[SmpSimultaneousRunHalt] not_applicable in 0.00s
[StepTest] Starting > logs/20230702-144515-spike32-StepTest.log
[StepTest] pass in 6.82s
[StepThread2Test] Starting > logs/20230702-144522-spike32-StepThread2Test.log
[StepThread2Test] not_applicable in 0.00s
[Sv32Test] Starting > logs/20230702-144522-spike32-Sv32Test.log
[Sv32Test] pass in 7.64s
[Sv39Test] Starting > logs/20230702-144529-spike32-Sv39Test.log
[Sv39Test] not_applicable in 0.00s
[Sv48Test] Starting > logs/20230702-144529-spike32-Sv48Test.log
[Sv48Test] not_applicable in 0.00s
[TooManyHwbp] Starting > logs/20230702-144529-spike32-TooManyHwbp.log
[TooManyHwbp] pass in 9.72s
[TriggerDmode] Starting > logs/20230702-144539-spike32-TriggerDmode.log
[TriggerDmode] pass in 7.06s
[TriggerExecuteInstant] Starting > logs/20230702-144546-spike32-TriggerExecuteInstant.log
[TriggerExecuteInstant] pass in 3.72s
[TriggerLoadAddressInstant] Starting > logs/20230702-144550-spike32-TriggerLoadAddr [...]

2023-07-05 15:17 UTC, timsifive approved these changes

2023-07-05 15:18 UTC, merged